### ISSUE TITLE
Deploying without Quarto config settings gives unhelpful error

### ISSUE THREAD

**Issue by dotNomad** [posit-dev/publisher#1159]
When deploying our `quarto-project` sample with this configuration:

```toml
'$schema' = 'https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json'
type = 'quarto'
entrypoint = 'quarto-project.qmd'
validate = true
title = 'quarto-project'
```

I get an unhelpful "Unsupported App Mode" error on publish even though the `type` is supported. To get past this error I needed to include:

```toml
[quarto]
version = '1.3.450'
engines = ['jupyter']
```
