### ISSUE TITLE
Publish extension as part of release CI

### ISSUE THREAD

**Issue by mmarchetti** [posit-dev/publisher#1688]
[Example](https://github.com/microsoft/vscode-platform-specific-sample/blob/main/.github/workflows/ci.yml#L70)

```
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: success() && startsWith( github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
      - run: npx vsce publish --packagePath $(find . -iname *.vsix)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
```
