### ISSUE TITLE
Files show as absolute file path instead of relative file path in toml

### ISSUE THREAD

**Issue by SamEdwardes** [posit-dev/publisher#2300]
I created a new quarto deployment in Positron. The following toml was auto-generated for me:

```toml
'$schema' = 'https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json'
type = 'quarto'
entrypoint = 'slides.qmd'
validate = true
files = [
  '/slides.qmd',
]
```

The above deployment works. But, I think that the files section should use relative paths, as opposed to absolute paths:

```toml
files = [
  './slides.qmd',
]
```

or

```toml
files = [
  'slides.qmd',
]
```

`/slides.qmd` should actually fail because this path points to a file at the root of my computer that does not exist.

## System info

Posit Publisher:

```
v1.1.6 (pre-release)
```

Positron:

```
Positron Version: 2024.09.0 (Universal) build 45
Code - OSS Version: 1.92.0
Commit: b0ec249b20455499f9e79ffe0bec35a5ff602ea4
Date: 2024-09-16T02:45:13.900Z
Electron: 30.1.2
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0
```
